### ISSUE TITLE
Plugin can't handle double sharps and double flats

### ISSUE THREAD

**Issue by turbofishcrow** [euwbah/musescore-n-tet-plugins#3]
For example it tunes Fx, G and Abb the same way, Cx, D, Ebb the same way, ...

**Comment by euwbah** [comment]
The plugin used to handle ups and downs notation with enharmonic equivalents. Support for 1/4-comma meantone approximation with quarter-tone accidentals is now available since 2530d3f58f2608a1bcbb2bbb42adbd6ba6f1ea5c in [this QML file](https://github.com/euwbah/musescore-31-tet-plugin/blob/master/31-TET-Meantone.qml). This mode doesn't have double sharps/flats enharmonic equivalence and it should be what you want.
