### ISSUE TITLE
Request to have sharp-9 support

### ISSUE THREAD

**Issue by ALLY1950** [euwbah/musescore-n-tet-plugins#36]
Since 94 edo is a very precise edo approxmating all the way to 23th harmonic within 4 cents, it will be best if the plug in can support. Since it is a sharp-9 system, a new notation system or symbol is probably needed.

**Comment by FloraCanou** [comment]
Indeed, a number of important tuning systems start with sharp-9, such as 80-, 87-, and 94edo. 

I hope you understand, however, that these systems are not fully supported as of now because our existing precombined accidentals only count up to 3 arrows, and combining accidentals aren't supported by MuseScore. 

Another consideration is that these sharp-9 systems are of the hemicomma level, meaning that the syntonic comma is tuned to two steps. Arguably these two-step alterations tend to be more common than single-step alterations. Using an arrow for a single step, altho totally logical, may not be the notation scheme that makes the most sense. 

A new notation scheme is probably the preferred way to go. I don't know if you have such a thing in mind yet. Here's a general workflow: 
1. Do you have a notation system in mind? Y: go to 2. N: work it out. 
2. Are the required symbols in Smufl yet? Y: go to 3. N: work with the Smufl team to get it included. 
3. Are the required symbols in MuseScore yet? Y: go to 4. N: work with MuseScore developers to get it included. 
4. Let's implement it! 

Note that designing a notation scheme from step 1 doesn't imply using new accidentals that are not in Smufl and/or MuseScore. We could borrow existing symbols just like how we did (we borrowed Stein-Zimmermann and/or HEJI symbols for our purposes). But I'm not sure if there's any spare symbols suitable for a sharp-9 logic. Feel free to share with us if you find it out.

**Comment by DaffodilAura** [comment]
My problem is that the SMuFL team seems to be reluctant to add Syntonic-Rastmic Subchroma notation, so in Issue #43, I've mentioned that we could also expand this plugin to also give Dorico-like functionality.  Besides, if MuseScore itself can undergo a fundamental rewrite in order to accomplish new things, so too can this plugin.

**Comment by Minepig** [comment]
> Since 94 edo is a very precise edo approxmating all the way to 23th harmonic within 4 cents, it will be best if the plug in can support. Since it is a sharp-9 system, a new notation system or symbol is probably needed.

B站来的，我fork了一下，挑了10个Musescore里有的变音号代替四箭头，以此来支持sharp-9和sharp-10。
https://github.com/Minepig/musescore-microtonal-edo-plugin

I fork this repo, and include 10 extra accidentals supported by Musescore, so that the plugin can tune sharp-9 & sharp-10 EDOs. Check it out.

**Comment by euwbah** [comment]
See https://github.com/euwbah/musescore-xen-tuner/
