### ISSUE TITLE
Retuning notes on fly?

### ISSUE THREAD

**Issue by suhr** [euwbah/musescore-n-tet-plugins#6]
Right now, even with a key signature you have to retune the score every time you make a change.

**Comment by euwbah** [comment]
Sadly, Musescore's plugin interface does not allow for this. Right now, the most efficient way to retune scores is to assign a key shortcut that runs the plugin. You can do this by going to the plugin manager and clicking on 'Define Shortcut' on the selected plugin. I use Alt + R for retuning since that shortcut is not currently in use by default, but you can use any key combination you like.

![image](https://user-images.githubusercontent.com/7107290/44832714-3459be00-ac5e-11e8-878d-8704b03bc71d.png)

**Comment by euwbah** [comment]
Closing because not currently implementable.
